// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://bpasogtbjzxealbauhhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_ZLq3ChCBMS2gv2ipA_RjUw_gN5uVU9R";

// Avoid localStorage on the server to prevent SSR crashes; fall back to in-memory storage.
const memoryStorage: Storage = {
  _data: {} as Record<string, string>,
  getItem(key) {
    return this._data[key] ?? null;
  },
  setItem(key, value) {
    this._data[key] = value;
  },
  removeItem(key) {
    delete this._data[key];
  },
  clear() {
    this._data = {};
  },
  key(index) {
    return Object.keys(this._data)[index] ?? null;
  },
  get length() {
    return Object.keys(this._data).length;
  },
};

const authStorage = typeof window !== "undefined" ? localStorage : memoryStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});